### ISSUE TITLE
CPU usage reaches 100% and network I/O is GBs

### ISSUE THREAD

**Issue by aletundo** [di-unipi-socc/FogMon#15]
Hello!

I'm trying to use FogMon and I faced a very strange behavior:

- CPU consumption is constantly around 100% for both leaders and followers (a single core is used, even if multiple core are available);
- Network I/O reaches immediately GBs of data.

Overall, the system looks like is working correctly, the logs seems okay, but definitely this resource usage is not normal (also according to the results reported in the papers).

Here below the setups I tried, all resulting in the same behavior.
- Branches:
  - `liscio-2.0`
  - `2.0-tmp`
- Docker Images:
  - `diunipisocc/liscio-fogmon:fogmon2` from Dockerhub
  - building locally from both branches using `Dockerfile` and `ubuntu.Dockerfile` in the root of the project, respectively
- Topology:
  - 4 nodes on the same machine using `docker-compose.yml ` provided (tried with both Docker Desktop and native Docker on Linux)
  - two distinct nodes on a LAN with manually executed follower and leader

The CPU usage is always around 100% no matter if checked using `docker stats`, `htop` on the hosting machine, or `htop` inside the container.
In the case of the following two images, it's a screenshot from `htop` inside a leader and follower running on two distinct machines, the Docker image is built from `branch 2.0-tmp` using the `ubuntu.Dockerfile`. 

<img width="1669" alt="Screenshot 2024-04-23 at 23 49 44" src="https://github.com/di-unipi-socc/FogMon/assets/15201375/970117dc-14f5-4366-a8a2-daed49d8620a">

<img width="1679" alt="Screenshot 2024-04-23 at 23 46 55" src="https://github.com/di-unipi-socc/FogMon/assets/15201375/838410f6-a769-4213-be28-dc3f67e067ec">

The following image is instead from `docker stats`, the uptime of the containers was about 10 minutes, the image used was the same, but in this case I was executing on a single machine using Docker Desktop.

<img width="1190" alt="image" src="https://github.com/di-unipi-socc/FogMon/assets/15201375/ba7fb626-5a16-4bec-b850-014ec5ed879d">

Let me know if I can provide you with further details.

Thank you!

**Comment by mrc-g** [comment]
I tried with the branch `2.0-tmp`, the last branch I worked on.
I started 4 nodes using the `docker-compose.yml` that uses the `ubuntu.Dockerfile`.
The CPU usage is mostly at 0% with some minor spikes, but never at 100%.
The network I/O is expected to reach GB considering a single Iperf3 test last 5 seconds with an average speed of around 561207 kbps (locally for my machine), meaning around 350 MB for every bandwidth test, there are 3 test for node, meaning around 1 GB exactly of bandwidth used after the first few seconds.
![image](https://github.com/di-unipi-socc/FogMon/assets/17200993/f5165ee5-9203-4fd3-b8d7-783ae1b06567)
![image](https://github.com/di-unipi-socc/FogMon/assets/17200993/9b6b3ba7-ea9f-45af-90ca-a749edda631b)

Does the CPU reach 100% usage after a few seconds of runtime or does it need some time? like reaching the leader selection or a particular report or test?

**Comment by aletundo** [comment]
Thank you for the prompt reply!

It's almost immediate.
Can you please provide me with a list of step (starting from cloning the repository) to reproduce your current setup from scratch?

**Comment by mrc-g** [comment]
Just sync with the last commit of `2.0-tmp`, the latest commit was 1-2 hours ago (it shouldn't change anything major but still)
```shell
git clone git@github.com:di-unipi-socc/FogMon.git
cd FogMon
git checkout 2.0-tmp
git submodule init
git submodule update
```

Then `docker compose build` and `docker compose up`, I don't think anything extra is needed.

Maybe is useful to know something about the system I'm using: Linux 64 bit x86_64, Ubuntu 22.04
But it works like that even on my docker-desktop on Windows using WSL2.

Small update: on docker-desktop when performing the bandwidth tests, the CPU goes to 100% for a few seconds (then everything returns to 0%) probably due to the larger bandwidth on my laptop (6.44073e+07 kbps, meaning 8 GB/s) as you can see the larger network I/O, it transferred more than 300 GB in the first few minutes.
![image](https://github.com/di-unipi-socc/FogMon/assets/17200993/63a1c356-6bc9-4500-8230-c36bc4ca97aa)

**Comment by aletundo** [comment]
When I perform `git submodule update` it returns an error:

![image](https://github.com/di-unipi-socc/FogMon/assets/15201375/c24436a1-725f-497e-bfb8-ae397fb84d30)


And of course if I ignore it, the Docker image build fails:

![image](https://github.com/di-unipi-socc/FogMon/assets/15201375/056415e6-5c0e-4e0c-9285-8c29ad720c1c)

**Comment by aletundo** [comment]
> When I perform `git submodule update` it returns an error:
> 
> ![image](https://private-user-images.githubusercontent.com/15201375/325180010-c24436a1-725f-497e-bfb8-ae397fb84d30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NTY1NDgsIm5iZiI6MTcxMzk1NjI0OCwicGF0aCI6Ii8xNTIwMTM3NS8zMjUxODAwMTAtYzI0NDM2YTEtNzI1Zi00OTdlLWJmYjgtYWUzOTdmYjg0ZDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDEwNTcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlZjIxZmNmMzBhNGQwYmExMTc1MjM5NmQ3YzNjNWZjMDI5ZWY5YTUxNjc0MzIyYTVmNWRhYjkzYjgwZjQ0MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aj-6y821e8bHi3MB84iSBUk9WY-r7_PVpjTlFuiqbks)
> 
> And of course if I ignore it, the Docker image build fails:
> 
> ![image](https://private-user-images.githubusercontent.com/15201375/325180334-056415e6-5c0e-4e0c-9285-8c29ad720c1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NTY1NDgsIm5iZiI6MTcxMzk1NjI0OCwicGF0aCI6Ii8xNTIwMTM3NS8zMjUxODAzMzQtMDU2NDE1ZTYtNWMwZS00ZTBjLTkyODUtOGMyOWFkNzIwYzFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDEwNTcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1NTM1OTJkNGU0MmQ4YjRkOTY3YTllZWRjNTVhMjA1MDIxMDk0ZDI2MTdhMjRhZWJjMjgzZWRlZDg1YTYwNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-vzPTgqHNsilsq9IL5rEXF7wgQwiCY6_YczMYN1V-LI)

The issue with submodules I solved by myself: the urls in the `.gitsubmodule` should use .git for the urls, and branches (if needed) should be configured with the property `branch`.

```
[submodule "rapidjson"]
        path = FogMon/rapidjson
        url = https://github.com/Tencent/rapidjson.git
        branch = master
[submodule "tests/googletest"]
        path = tests/googletest
        url = https://github.com/google/googletest.git
        branch = master
[submodule "sigar"]
        path = FogMon/sigar
        url = https://github.com/hyperic/sigar.git
        branch = master
```

**Comment by mrc-g** [comment]
I updated the submodules in the branch as google test is not needed anymore.
I think the problem was that I did git submodule init/update before the `git checkout 2.0-tmp`

**Comment by aletundo** [comment]
Ok, I've further insights!

First of all, I was able to successfully execute the system (besides follower3 that was unable to contact the leader, but I guess I was just unlucky) without editing the `docker-compose.yml`. The CPU values are as expected, and the net I/O is reasonable (taking into account how the bandwidth probe works).

However, I was again able to reproduce the strange behavior after I modified the `docker-compose.yml`. Here follows the list of modification and the resulting file.

- removed `entrypoint` in favor of `command`:
  - to use default configs
  - to not inject delay
  - to not connect to "interface" because I don't need FogMonEye (I supposed the `--interface webserver:80` is necessary for FogMonEye only)
- removed `cap_add` because it's there for `tc`, and I supposed it's only necessary if I use the delay script
- removed unused frontend and backend networks, and FogMonEye services (webserver, backend, mongodb)
- removed unused volumes
- removed `stdin_open`
- removed published ports since the network is bridged and I don't need any access from the host

Is there anything I should not remove? If yes, what's the reason? 
Can you please try with this compose file and see if you experience the same?

Thank you for the support!

```
version: '3'
services:
  leader:
    build:
      context: .
      dockerfile: ubuntu.Dockerfile
      target: runner
    command: --leader
    networks:
      - default
  follower1:
    build:
      context: .
      dockerfile: ubuntu.Dockerfile
      target: runner
    image: leader
    command: -C leader
    depends_on:
      - leader
    networks:
      - default
  follower2:
    build:
      context: .
      dockerfile: ubuntu.Dockerfile
      target: runner
    command: -C leader
    depends_on:
      - leader
    networks:
      - default
  follower3:
    build:
      context: .
      dockerfile: ubuntu.Dockerfile
      target: runner
    command: -C leader
    depends_on:
      - leader
    networks:
      - default

networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
        - subnet: 2001:3984:3989::/64
          gateway: 2001:3984:3989::1
```
